bases:
- ../../native
patchesStrategicMerge:
- kafka.yaml
- zookeeper.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: kafka
  path: kafka-scale1-overrides.json
