---
apiVersion: v1
kind: Service
metadata:
  name: pzoo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: zookeeper
        resources:
          limits:
            memory: 120Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      - name: init-config
        env:
        - name: PZOO_REPLICAS
          value: '0'
        - name: REPLICAS
          value: '1'
        - name: ID_OFFSET
          value: '1'
      containers:
      - name: zookeeper
        env:
        - name: REPLICAS
          value: '1'
        resources:
          limits:
            memory: 120Mi
