apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka-monitor
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-monitor
  template:
    metadata:
      labels:
        app: kafka-monitor
    spec:
      containers:
      - name: kafka-monitor
        image: solsson/kafka-monitor@sha256:93e8e53da8611b63b991278ed54f52c828ba1c90285b704d4c3fef1c7d4d23d9
        ports:
        - name: http
          containerPort: 8000
        - name: metrics
          containerPort: 8778
