apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixy
  namespace: kafka
  labels:
    app: pixy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pixy
  template:
    metadata:
      labels:
        app: pixy
    spec:
      containers:
      - name: pixy
        image: solsson/kafka-pixy:webhook-produce-logging@sha256:e2818d5a33df7c44afda57ce4c4f862bfd19b515eae45f2eda0f93c9e5dcfc2f
        ports:
        - containerPort: 80
        command:
        - kafka-pixy
        - -kafkaPeers
        - bootstrap.kafka:9092
        - -zookeeperPeers
        - zookeeper.kafka:2181
        - -tcpAddr
        - 0.0.0.0:80
