---
apiVersion: v1
kind: Service
metadata:
  name: broker-0
  namespace: kafka
spec:
  selector:
    app: kafka
    petindex: "0"
  ports:
    - port: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: broker-1
  namespace: kafka
spec:
  selector:
    app: kafka
    petindex: "1"
  ports:
    - port: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: broker-2
  namespace: kafka
spec:
  selector:
    app: kafka
    petindex: "2"
  ports:
    - port: 9092
