apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-2
  namespace: kafka
spec:
  replicas: 1
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: kafka
        petindex: "2"
    spec:
      containers:
      - name: broker
        image: solsson/kafka-persistent:0.10.1@sha256:110f9e866acd4fb9e059b45884c34a210b2f40d6e2f8afe98ded616f43b599f9
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        ports:
          - containerPort: 9092
        command:
          - ./bin/kafka-server-start.sh
          - config/server.properties
          - --override
          - broker.id=2
          - --override
          - advertised.listeners=PLAINTEXT://broker-2.kafka.svc.cluster.local:9092
        volumeMounts:
          - name: datadir
            mountPath: /opt/kafka/data
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir-kafka-2
