apiVersion: batch/v1
kind: Job
metadata:
  name: topic-create-event-kube
spec:
  template:
    spec:
      containers:
      - name: topic-create
        image: vectorized/redpanda:v21.11.10@sha256:0841e5a06ee5ee60385121aa2e766ceee5964c359a4ab42e73475f6d25fdd057
        command:
        - rpk
        - topic
        - create
        - --brokers
        -   bootstrap:9092
        - ops.kube-events.stream.json
        resources:
          limits:
            cpu: 100m
            memory: 20Mi
      restartPolicy: Never
