kind: Service
apiVersion: v1
metadata:
  name: outside-2
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "2"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32402
    nodePort: 32402
  type: NodePort