apiVersion: v1
kind: Service
metadata:
  name: meteric
  namespace: kafka
spec:
  ports:
  - name: http
    port: 5556
    nodePort: 30001
    protocol: TCP
  type: NodePort
  selector:
    app: kafka
