apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: node-exporter-http
  namespace: kafka
  labels:
    app: node-exporter
spec:
  type: NodePort
  selector:
    app: node-exporter
  ports:
    - name: scrape
      port: 9100
      nodePort: 30002
      protocol: TCP
