apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-events-consumer
  namespace: kafka
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # prefer duplicate events over missed
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: events
        type: test
        from: kafka-ops
    spec:
      containers:
      - name: kafkacat
        image: solsson/kafkacat@sha256:36d1f191cc33a8365074280279205e6b4f52cd8cc8fb1b896bb4c943c9dee8f8
        command:
        - kafkacat
        - -b
        - kafka-0.broker.kafka.svc.cluster.local:9092,kafka-1.broker.kafka.svc.cluster.local:9092,kafka-2.broker.kafka.svc.cluster.local:9092
        - -t
        - ops-kube-events-all-json-001
        - -C
