apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
spec:
  template:
    spec:
      containers:
      - name: zookeeper
        image: solsson/kafka:native-zookeeper-server-start@sha256:eade61d60bb59005d06c8edd6dfebd7f18437e09cc5516916b50096cfbdb1ffe
        resources:
          requests:
            cpu: 10m
            memory: 25Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
spec:
  template:
    spec:
      containers:
      - name: zookeeper
        image: solsson/kafka:native-zookeeper-server-start@sha256:eade61d60bb59005d06c8edd6dfebd7f18437e09cc5516916b50096cfbdb1ffe
        resources:
          requests:
            cpu: 10m
            memory: 25Mi
