apiVersion: v1
kind: Service
metadata:
  name: kminion
  namespace: kafka
  labels: &labels
    app: kminion
spec:
  type: NodePort
  selector: *labels
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30077
