apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: avro-schemas
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: cp
        image: solsson/kafka-cp@sha256:2797da107f477ede2e826c29b2589f99f22d9efa2ba6916b63e07c7045e15044
        env:
        - name: SCHEMA_REGISTRY_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/schema-registry/log4j.properties
        command:
        - schema-registry-start
        - /etc/schema-registry/schema-registry.properties
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/schema-registry
      volumes:
      - name: config
        configMap:
          name: avro-tools-config
