apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  template:
    spec:
      initContainers:
      - name: init-config
        image: solsson/kafka:initutils-nonroot@sha256:c239d8c5c767cfe9ffd81cce96af9a61e487400d167f58a7e89478c958ca73b9
      containers:
      - name: broker
        image: solsson/kafka:2.8.0-kafka-server-start@sha256:825a7e70563a786a43c327f06257c3c502f8bc191d4fb91cf53fdc07aa69703f
        args:
        - /etc/kafka/server.properties.$(POD_NAME)
