apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
spec:
  template:
    spec:
      initContainers:
      - name: init-config
        image: solsson/kafka:initutils-nonroot@sha256:87f6bb39fd47a6f382018a2dc55a484d1b71eee48a58019c7e65a9bc53e8dca2
      containers:
      - name: zookeeper
        image: solsson/kafka:zookeeper-server-start@sha256:c34a9928fcc5ac15b2243ee2994cf09f5a3608b6090de378f39f89ad12320276
        args:
        - /etc/kafka/zookeeper.properties.scale-$(REPLICAS).$(POD_NAME)
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
spec:
  template:
    spec:
      initContainers:
      - name: init-config
        image: solsson/kafka:initutils-nonroot@sha256:87f6bb39fd47a6f382018a2dc55a484d1b71eee48a58019c7e65a9bc53e8dca2
      containers:
      - name: zookeeper
        image: solsson/kafka:zookeeper-server-start@sha256:c34a9928fcc5ac15b2243ee2994cf09f5a3608b6090de378f39f89ad12320276
        args:
        - /etc/kafka/zookeeper.properties.scale-$(REPLICAS).$(POD_NAME)
