apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kafka
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
