---
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: default-privilege-add
rules:
- apiGroups: [""]
  resources:
  - endpoints
  - services
  - pods
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-privilege-add
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-privilege-add
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: my-namespace
  namespace: my-namespace