apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.streamingmicroservicesplatform.github.com
spec:
  group: streamingmicroservicesplatform.github.com
  version: v1
  scope: Namespaced
  names:
    plural: kafkatopics
    singular: kafkatopic
    kind: KafkaTopic
    shortNames:
    - topic
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name:
              type: string
              pattern: '^([a-z0-9_]+|[a-z0-9-]+)$'
            partitions:
              type: integer
              minimum: 1
              maximum: 10
            replication:
              type: string
              enum:
                # the minimum that the current cluster can provide availability for during normal operations
                - min
                # current cluster's recommended replication for production data
                - prod
            format:
              type: string
              enum:
                - blob
                - json
                - msgpack
                - protobuf
            schema:
              type: string
